[package]
name = "serial-sensors"
authors = ["Markus Mayer <widemeadows@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
array_pool = "0.1.2"
corncobs = "0.1.3"
tokio = { version = "1.38.0", features = ["full"] }
tokio-serial = "5.4.4"
